### ISSUE TITLE
in the Referrers blade, artifact type and digest should be displayed in one node

### ISSUE THREAD

**Issue by qweeah** [VasuDevrani/artifact-explorer-oras#19]
Currently the artifact type and digest and displayed in two lines with digest toggled by default
<img width="604" alt="image" src="https://github.com/VasuDevrani/artifact-explorer-oras/assets/4254263/c4f5c389-fc08-4639-ac15-2e88a8a6b659">

The digest should be displayed in the same node with artifact type no node should not be toggled by default. (`Bar` and `Buzz` should all be shown by default)

**Comment by VasuDevrani** [comment]
is this issue fixed now? @qweeah 
also, if not then issue should still be closed for #39
