### ISSUE TITLE
Index without subject are displaying as referrers

### ISSUE THREAD

**Issue by qweeah** [VasuDevrani/artifact-explorer-oras#37]
For `$HOST/artifact?image=ghcr.io/qweeah/oras:v0.16.1-rc1`, the OCI index `sha256:a9fd327cb35ea2acb9f523a170802213e762327d97aaf7455a8e548c3ce38311` is showing is the `referrers` blade.

This is a bug. The manifest contains no `sujbect`, thus should not be display in the referrers blade
![image](https://github.com/VasuDevrani/artifact-explorer-oras/assets/4254263/a486aa60-8254-4d56-856d-e8f93ead5ea3)

**Comment by VasuDevrani** [comment]
on hold for issue #39
