### ISSUE TITLE
artifact type is not displayed properly

### ISSUE THREAD

**Issue by qweeah** [VasuDevrani/artifact-explorer-oras#43]
When using referrers API, the artifact type is always presented in the `artifactType` field. But when the manifest is fetched directly, the artifact type is might be presented via `config.mediaType`

In below screenshot, the current artifact is `ghcr.io/qweeah/oras@sha256:2911971bced75f7b60bc9a25a36b79c3d118add9bb1a7c36c773c0eb0bf3f1c6`, whose artifact type is presented in`config.mediaType`, but the referrers view is showing its `mediaType` as `application/vnd.oci.image.manifest.v1+json`

![image](https://github.com/VasuDevrani/artifact-explorer-oras/assets/4254263/6f94f2a4-860f-4922-8609-41bd7881d69f)

Need to change the

**Comment by VasuDevrani** [comment]
resolved in pr #42
