### ISSUE TITLE
default name for layer downloading

### ISSUE THREAD

**Issue by qweeah** [VasuDevrani/artifact-explorer-oras#55]
We should also add the download button to table view in the artifact page, where we can provide file name properly from the annotations.

 @VasuDevrani what do you think?

_Originally posted by @qweeah in https://github.com/VasuDevrani/artifact-explorer-oras/issues/54#issuecomment-1685776118_

**Comment by VasuDevrani** [comment]
Would it be used to download manifest json?

**Comment by qweeah** [comment]
If the manifest has a `org.opencontainers.image.ref.name` annotation, then the default manifest file name can also be set.

**Comment by qweeah** [comment]
> Would it be used to download manifest json?

Yes, but I guess the download button for manifest is not in the table view
